import './ui/global.css';
import Navbar from "./ui/navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className='rootlayout-box'>
          <div className='rootlayout-sidenav-box'><Navbar /></div>
          <div className='rootlayout-content-box'>{children}</div>
        </div>
      </body>
    </html>
  );
}
